const projectsData = [
    {
        id: "03",
        display: "block",
        title: "Freelance - Pedro Acerbi Psychology",
        description: "O layout é responsivo, com uma paleta de cores suaves que transmite tranquilidade. Naveguei por várias seções, onde encontrei informações claras sobre o terapeuta, sua abordagem e os serviços oferecidos. Há um formulário de contato funcional e seções explicativas bem dispostas. A estrutura é eficiente, proporcionando uma experiência de usuário fluida e intuitiva.",
        technologies: ["HTML", "CSS", "JAVASCRIPT", "BOOTSTRAP"],
        githubUrl: "https://github.com/thalissongoncalves/Pedro-Acerbi-Psychology",
        alt: "Imagem Demo do projeto Pedro Acerbi",
        deployUrl: "https://pedro-acerbi-psychology.vercel.app/",
        image: "./images/25-pedro-acerbi.png",
    },
    {
        id: "04",
        display: "block",
        title: "Rick and Morty - Consulta de Personagens",
        description: "Desenvolvi este projeto para explorar a API de Rick and Morty, onde os usuários podem buscar e visualizar informações detalhadas dos personagens da série. O objetivo é apresentar os dados de forma interativa, aprimorando minhas habilidades em manipulação de APIs e interfaces dinâmicas.",
        technologies: ["HTML", "ANGULAR", "TYPESCRIPT", "CSS"],
        githubUrl: "https://github.com/thalissongoncalves/Rick-and-Morty",
        alt: "Imagem Demo do projeto Rick and Morty",
        deployUrl: "https://tg-rick-and-morty.vercel.app/",
        image: "./images/24-rick-and-morty-project.png",
    },
    {
        id: "05",
        display: "block",
        title: "Projeto Pessoal - Sistema Solar",
        description: " Desenvolvi este projeto como uma simulação interativa do sistema solar. O objetivo é visualizar os planetas e suas características, usando uma interface intuitiva e visualmente atraente. Com isso, aprimorei minhas habilidades em React, criando uma aplicação dinâmica e funcional.",
        technologies: ["HTML", "CSS", "JAVASCRIPT", "REACT"],
        githubUrl: "https://github.com/thalissongoncalves/Trybe-Projects/tree/main/09-Solar-System-main",
        alt: "Imagem Demo do projeto Solar System",
        deployUrl: "https://09-solar-system.vercel.app/",
        image: "./images/09-system-solar-project-img.png",
    },
    {
        id: "06",
        display: "block",
        title: "Projeto Pessoal - Carrinho de Compras",
        description: "Desenvolvi este projeto para simular um carrinho de compras online. Ele permite adicionar e remover produtos, calcular o subtotal, e inclui uma funcionalidade para buscar o CEP de entrega. O objetivo foi aprimorar minhas habilidades em manipulação de dados e interatividade com o usuário.",
        technologies: ["HTML", "CSS", "JAVASCRIPT"],
        githubUrl: "https://github.com/thalissongoncalves/Trybe-Projects/tree/main/08-Shopping-Cart-main",
        alt: "Imagem Demo do projeto Shopping Cart",
        deployUrl: "https://08-shopping-cart.vercel.app/",
        image: "./images/08-shopping-cart-project-img.png",
    },
    {
        id: "07",
        display: "block",
        title: "Projeto Pessoal - Formulário Trybewarts",
        description: "Desenvolvi este projeto inspirado no universo de magia para praticar a criação de formulários. O objetivo é permitir que usuários preencham suas informações, escolham casas, famílias e áreas de estudo de programação. A interface simula uma experiência lúdica de ingresso em uma escola de magia, tornando a interação divertida.",
        technologies: ["HTML", "CSS", "JAVASCRIPT"],
        githubUrl: "https://github.com/thalissongoncalves/Trybe-Projects/tree/main/05-Trybewarts-main",
        alt: "Imagem Demo do projeto Formulário Trybewarts",
        deployUrl: "https://05-trybewarts.vercel.app/",
        image: "./images/05-trybewarts-project-img.png",
    },
    {
        id: "08",
        display: "block",
        title: "Projeto Pessoal - Paleta de Cores",
        description: "Criei este projeto para gerar paletas de cores aleatórias, permitindo que o usuário visualize diferentes combinações e ajustes de largura e altura das cores exibidas. Ele facilita a experimentação criativa com paletas visuais personalizadas.",
        technologies: ["HTML", "CSS", "JAVASCRIPT"],
        githubUrl: "https://github.com/thalissongoncalves/Trybe-Projects/tree/main/04-Paleta-de-Cores",
        alt: "Imagem Demo do projeto Paleta de Cores",
        deployUrl: "https://04-paleta-de-cores.vercel.app/",
        image: "./images/04-paleta-de-cores-project-img.png",
    },
    {
        id: "09",
        display: "block",
        title: "Projeto Pessoal - Zuck Challenge",
        description: "Desenvolvi este projeto como parte do desafio Zuck Challenge, focado em soluções para inclusão de pessoas com daltonismo. A ideia principal é criar testes que identificam diferentes graus da doença e oferecer ferramentas para facilitar a interação dessas pessoas com plataformas como a Meta, promovendo acessibilidade e inclusão no ambiente digital.",
        technologies: ["HTML", "CSS", "JAVASCRIPT"],
        githubUrl: "https://github.com/thalissongoncalves/Trybe-Projects/tree/main/03-Zuck-Challenge-main",
        alt: "Imagem Demo do projeto Zuck Challenge",
        deployUrl: "https://03-zuck-challenge.vercel.app/",
        image: "./images/03-zuck-challenge-project-img.png",
    },
    {
        id: "10",
        display: "block",
        title: "Projeto Pessoal - Lições Aprendidas",
        description: "Criei este projeto como parte da minha jornada na Trybe para compartilhar as lições e tecnologias que venho aprendendo. No site, apresento uma lista de conhecimentos já adquiridos e áreas que ainda quero explorar, demonstrando meu progresso e dedicação ao longo do curso.",
        technologies: ["HTML", "CSS", "JAVASCRIPT"],
        githubUrl: "https://github.com/thalissongoncalves/Trybe-Projects/tree/main/01-Project-Lessons-Learned-main",
        alt: "Imagem Demo do projeto Lições Aprendidas",
        deployUrl: "https://01-project-lessons-learned.vercel.app/",
        image: "./images/01-lessons-learned-project-img.png",
    },
]

export default projectsData;
