const projectsData = [
    {
        id: "01",
        display: "block",
        title: "Lessons Learned",
        description: "Foi desenvolvido um site que contém uma série de informações sobre o que aprendi na Trybe ao longo das primeiras aulas de Fundamentos.",
        technologies: ["HTML", "CSS"],
        githubUrl: "https://github.com/thalissongoncalves/Project-Lessons-Learned/tree/main/Lessons-learned",
        alt: "Imagem Demo do projeto Lessons Learned",
        deployUrl: "",
        image: "./images/lesson-learned-project-img.png",
    },
    {
        id: "02",
        display: "block",
        title: "Segundo Projeto",
        description: "Foi desenvolvido um site que contém uma série de informações sobre o que aprendi na Trybe ao longo das primeiras aulas de Fundamentos.",
        technologies: ["JAVASCRIPT", "REACT"],
        githubUrl: "https://github.com/thalissongoncalves/Project-Lessons-Learned/tree/main/Lessons-learned",
        alt: "Imagem Demo do projeto Lessons Learned",
        deployUrl: "",
        image: "./images/lesson-learned-project-img.png",
    },
    {
        id: "03",
        display: "block",
        title: "Terceiro Projeto",
        description: "Foi desenvolvido um site que contém uma série de informações sobre o que aprendi na Trybe ao longo das primeiras aulas de Fundamentos.",
        technologies: ["JAVASCRIPT", "REACT"],
        githubUrl: "https://github.com/thalissongoncalves/Project-Lessons-Learned/tree/main/Lessons-learned",
        alt: "Imagem Demo do projeto Lessons Learned",
        deployUrl: "",
        image: "./images/lesson-learned-project-img.png",
    },
    {
        id: "04",
        display: "block",
        title: "Quarto Projeto",
        description: "Foi desenvolvido um site que contém uma série de informações sobre o que aprendi na Trybe ao longo das primeiras aulas de Fundamentos.",
        technologies: ["HTML", "CSS"],
        githubUrl: "https://github.com/thalissongoncalves/Project-Lessons-Learned/tree/main/Lessons-learned",
        alt: "Imagem Demo do projeto Lessons Learned",
        deployUrl: "",
        image: "./images/lesson-learned-project-img.png",
    },
    {
        id: "05",
        display: "block",
        title: "Quinto Projeto",
        description: "Foi desenvolvido um site que contém uma série de informações sobre o que aprendi na Trybe ao longo das primeiras aulas de Fundamentos.",
        technologies: ["HTML", "CSS"],
        githubUrl: "https://github.com/thalissongoncalves/Project-Lessons-Learned/tree/main/Lessons-learned",
        alt: "Imagem Demo do projeto Lessons Learned",
        deployUrl: "",
        image: "./images/lesson-learned-project-img.png",
    },
    {
        id: "06",
        display: "block",
        title: "Sexto Projeto",
        description: "Foi desenvolvido um site que contém uma série de informações sobre o que aprendi na Trybe ao longo das primeiras aulas de Fundamentos.",
        technologies: ["HTML", "CSS"],
        githubUrl: "https://github.com/thalissongoncalves/Project-Lessons-Learned/tree/main/Lessons-learned",
        alt: "Imagem Demo do projeto Lessons Learned",
        deployUrl: "",
        image: "./images/lesson-learned-project-img.png",
    },
]

export default projectsData;