const projectsData = [
    {
        id: "01",
        display: "block",
        title: "01 - Lessons Learned",
        description: "Site que contém uma série de informações sobre o que aprendi na Trybe ao longo das primeiras aulas de Fundamentos.",
        technologies: ["HTML", "CSS"],
        githubUrl: "https://github.com/thalissongoncalves/01-Project-Lessons-Learned",
        alt: "Imagem Demo do projeto Lessons Learned",
        deployUrl: "https://01-project-lessons-learned.vercel.app/",
        image: "./images/01-lessons-learned-project-img.png",
    },
    {
        id: "02",
        display: "block",
        title: "02 - Playground Functions",
        description: "Resolvido alguns desafios em javascript para treinamento de uso de funções e lógica.",
        technologies: ["JAVASCRIPT"],
        githubUrl: "https://github.com/thalissongoncalves/02-playground-functions",
        alt: "Imagem Demo do projeto Playground functions",
        deployUrl: "#",
        image: "./images/02-playground-functions-project-img.png",
    },
    {
        id: "03",
        display: "block",
        title: "03 - Paleta de Cores",
        description: "Editor de arte com pixels em que a pessoa usuária poderá escolher uma cor em uma paleta de cores e poderá pintar o que quiser em um quadro branco 🎨 🧑‍🎨",
        technologies: ["HTML", "CSS", "JAVASCRIPT"],
        githubUrl: "https://github.com/thalissongoncalves/02-Paleta-de-Cores",
        alt: "Imagem Demo do projeto Paleta de Cores",
        deployUrl: "https://03-paleta-de-cores.vercel.app/",
        image: "./images/03-paleta-de-cores-project-img.png",
    },
    {
        id: "04",
        display: "block",
        title: "04 - Trybewarts",
        description: "Uma página de formulário da Escola de Magia de Trybewarts, em que as pessoas estudantes poderão enviar seus feedbacks sobre ela. O tema desse projeto é baseado na obra 'Harry Potter', de J. K. Rowling.",
        technologies: ["HTML", "CSS", "JAVASCRIPT"],
        githubUrl: "https://github.com/thalissongoncalves/03-Trybewarts",
        alt: "Imagem Demo do projeto Trybewarts",
        deployUrl: "https://04-trybewarts.vercel.app/",
        image: "./images/04-trybewarts-project-img.png",
    },
    {
        id: "05",
        display: "block",
        title: "05 - Js Unit Tests",
        description: "Foi implementado várias funções na resolução dos requisitos propostos e/ou testes unitários para garantir que as implementações das funções estão corretas, de acordo com o que está sendo solicitado em cada enunciado.",
        technologies: ["JAVASCRIPT", "NODE", "JEST"],
        githubUrl: "https://github.com/thalissongoncalves/04-js-unit-tests",
        alt: "Imagem Demo do projeto JS UNIT TESTS",
        deployUrl: "#",
        image: "./images/05-js-unit-tests-project-img.png",
    },
    {
        id: "06",
        display: "block",
        title: "06 - Zoo Functions",
        description: "No projeto, empreguei ES6 e Higher Order Functions para organizar dados do zoológico, enfatizando a abordagem orientada a testes. Obtive uma implementação eficaz, destacando minha habilidade prática e comprometimento com a qualidade do código.",
        technologies: ["JAVASCRIPT", "NODE", "JEST"],
        githubUrl: "https://github.com/thalissongoncalves/05-zoo-functions",
        alt: "Imagem Demo do projeto Zoo Functions",
        deployUrl: "#",
        image: "./images/06-zoo-functions-project-img.png",
    },
    
]

export default projectsData;